In [1]:
# import library yang dibutuhkan
import pandas as pd
from IPython.display import display

# read csv
df = pd.read_csv("../data/data_train.csv")

target = df[["price_range"]]
nonTarget = df.drop(["price_range"], axis=1)
pd.set_option('display.max_columns', None)
print("Overview data:")
df

Overview data:

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,804,1,0.8,1,12,1,41,0.9,89,1,13,709,818,2027,11,5,11,1,0,0,1
1,1042,0,2.2,0,15,1,11,0.6,139,5,16,68,1018,2826,18,0,2,1,0,0,2
2,1481,1,2.0,1,0,0,35,0.5,105,3,0,249,522,2635,17,16,4,1,0,1,2
3,1104,0,1.7,0,1,1,60,0.4,199,2,13,653,1413,1229,6,0,3,1,1,1,0
4,652,0,0.5,1,1,0,58,0.6,142,3,2,464,781,565,18,12,9,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1395,536,1,1.4,0,0,1,53,0.7,135,3,0,547,705,1211,15,10,7,1,0,1,0
1396,1097,0,0.8,0,10,1,21,0.1,160,7,15,1277,1352,2219,15,6,12,1,0,1,2
1397,1179,1,0.5,0,7,1,32,0.3,182,2,12,85,1451,340,16,5,16,1,0,0,0
1398,719,1,0.5,1,0,1,23,0.4,113,6,9,431,1727,3990,14,9,12,1,1,1,3
1399,1439,0,0.9,0,12,1,20,0.8,147,1,17,626,932,1790,19,12,15,1,0,1,1

In [2]:
# menginisiasi dict yang nantinya akan diubah menjadi dataframe
ds = {}
ds['Descriptive Stat'] = ['Mean','Median','STD','Minimum','25%','50%','75%',
                          'Maximum','Variance','Range','IQR','Skewness','Kurtosis']
ds['battery_power']         = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['blue']                  = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['clock_speed']           = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['dual_sim']              = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['fc']                    = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['four_g']                = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['int_memory']            = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['m_dep']                 = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['mobile_wt']             = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['n_cores']               = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['pc']                    = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['px_height']             = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['px_width']              = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['ram']                   = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['sc_h']                  = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['sc_w']                  = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['talk_time']             = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['three_g']               = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['touch_screen']          = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['wifi']                  = [0,0,0,0,0,0,0,0,0,0,0,0,0]
ds['price_range']           = [0,0,0,0,0,0,0,0,0,0,0,0,0]

# memasukan data per kolom ke dict
for col in df:
    #input mean
    ds[col][0]=(df[col].mean())
    #input median
    ds[col][1]=(df[col].median())
    #input standar deviasi
    ds[col][2]=(df[col].std())
    #input minimum value
    ds[col][3]=(df[col].min())
    #input kuartil Q1
    ds[col][4]=(df[col].quantile(0.25))
    #input kuartil Q2
    ds[col][5]=(df[col].quantile(0.50))
    #input kuartil Q3
    ds[col][6]=(df[col].quantile(0.75))
    #input maximum value
    ds[col][7]=(df[col].max())
    #input variansi
    ds[col][8]=(df[col].var())
    #input range
    ds[col][9]=(df[col].max() - df[col].min())
    #input IQR
    ds[col][10]=(df[col].quantile(0.75) - df[col].quantile(0.25))
    #input skewness
    ds[col][11]=(df[col].skew())
    #input kurtosis
    ds[col][12]=(df[col].kurtosis())

# dict to dataframe
df_ds = pd.DataFrame(ds)
# pembulatan 3 digit belakang koma
df_ds = df_ds.round(3)
# display
print("Deskripsi Statistik:")
display(df_ds)

# khusus untuk nilai modus tiap kolom dipisah karena bisa lebih dari 1
print("Modus:")
df.mode()

Deskripsi Statistik:

,Descriptive Stat,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,Mean,1237.146,0.494,1.522,0.503,4.275,0.530,31.962,0.508,139.376,4.481,9.917,643.178,1251.717,2106.731,12.286,5.665,11.042,0.761,0.489,0.495,1.478
1,Median,1219.000,0.000,1.500,1.000,3.000,1.000,32.000,0.500,139.000,4.000,10.000,561.000,1247.000,2102.000,12.000,5.000,11.000,1.000,0.000,0.000,1.000
2,STD,430.052,0.500,0.815,0.500,4.324,0.499,18.163,0.289,35.401,2.280,6.080,444.629,428.983,1078.347,4.204,4.372,5.399,0.427,0.500,0.500,1.118
3,Minimum,501.000,0.000,0.500,0.000,0.000,0.000,2.000,0.100,80.000,1.000,0.000,0.000,500.000,256.000,5.000,0.000,2.000,0.000,0.000,0.000,0.000
4,25%,864.750,0.000,0.700,0.000,1.000,0.000,16.000,0.200,108.000,2.000,5.000,273.750,876.500,1201.000,9.000,2.000,6.000,1.000,0.000,0.000,0.000
5,50%,1219.000,0.000,1.500,1.000,3.000,1.000,32.000,0.500,139.000,4.000,10.000,561.000,1247.000,2102.000,12.000,5.000,11.000,1.000,0.000,0.000,1.000
6,75%,1602.000,1.000,2.200,1.000,7.000,1.000,48.000,0.800,169.000,7.000,15.000,950.250,1627.500,3035.750,16.000,9.000,16.000,1.000,1.000,1.000,2.000
7,Maximum,1998.000,1.000,3.000,1.000,19.000,1.000,64.000,1.000,200.000,8.000,20.000,1960.000,1998.000,3998.000,19.000,18.000,20.000,1.000,1.000,1.000,3.000
8,Variance,184944.538,0.250,0.664,0.250,18.698,0.249,329.893,0.083,1253.217,5.198,36.967,197694.930,184026.286,1162832.850,17.675,19.116,29.150,0.182,0.250,0.250,1.249
9,Range,1497.000,1.000,2.500,1.000,19.000,1.000,62.000,0.900,120.000,7.000,20.000,1960.000,1498.000,3742.000,14.000,18.000,18.000,1.000,1.000,1.000,3.000
10,IQR,737.250,1.000,1.500,1.000,6.000,1.000,32.000,0.600,61.000,5.000,10.000,676.500,751.000,1834.750,7.000,7.000,10.000,0.000,1.000,1.000,2.000
11,Skewness,0.042,0.026,0.166,-0.011,1.020,-0.120,0.063,0.059,0.020,0.020,0.029,0.659,0.004,0.029,-0.103,0.671,-0.009,-1.223,0.043,0.020,0.029
12,Kurtosis,-1.168,-2.002,-1.330,-2.003,0.293,-1.988,-1.227,-1.267,-1.210,-1.232,-1.164,-0.316,-1.176,-1.186,-1.183,-0.335,-1.192,-0.504,-2.001,-2.002,-1.358

Modus:

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,772,0.0,0.5,1.0,0.0,1.0,27.0,0.1,182.0,4.0,10.0,88.0,1247.0,1229.0,17.0,1.0,15.0,1.0,0.0,0.0,0.0
1,1068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347.0,NaN,3142.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,526.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN